version: '3'
services:
  app:
    build: .
    expose:
      - 4000
      - 35729
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: yarn start
